version: 2.1

orbs:
  slack: circleci/slack@3.4.2

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: exit 0
      - slack/status

workflows:
  version: 2
  ci:
    jobs:
      - hello
